import { useEffect, useState } from 'react'
import ListEditor from './ListEditor'

const SOAP_SECTIONS = [
  ['subjective', 'Subjective'],
  ['objective', 'Objective'],
  ['assessment', 'Assessment'],
  ['plan', 'Plan'],
]

export default function NoteEditor({ note, reviewed, busy, onSave }) {
  // local draft so typing does not hit the server on every keystroke
  const [draft, setDraft] = useState(note)
  const [dirty, setDirty] = useState(false)

  // reset when a different encounter is selected or the note is regenerated
  useEffect(() => {
    setDraft(note)
    setDirty(false)
  }, [note])

  function edit(updater) {
    setDraft(updater)
    setDirty(true)
  }

  const setSoap = (key, value) =>
    edit((d) => ({ ...d, soap: { ...d.soap, [key]: value } }))

  const setEntity = (key, value) =>
    edit((d) => ({ ...d, entities: { ...d.entities, [key]: value } }))

  const input = 'w-full rounded border border-gray-300 px-2 py-1 text-sm'

  return (
    <div className="rounded-lg border border-gray-200 bg-white">
      <div className="flex items-center justify-between border-b border-gray-200 px-5 py-3">
        <h2 className="text-base font-semibold text-gray-900">Clinical note</h2>
        <div className="flex items-center gap-3">
          {reviewed === 1 && !dirty && (
            <span className="rounded bg-green-50 px-2 py-0.5 text-xs text-green-800">reviewed</span>
          )}
          {dirty && <span className="text-xs text-amber-700">unsaved changes</span>}
          <button
            className="rounded-md bg-gray-900 px-4 py-1.5 text-sm font-medium text-white disabled:opacity-40"
            onClick={() => onSave(draft)}
            disabled={busy}
          >
            {busy ? 'Saving…' : 'Save reviewed note'}
          </button>
        </div>
      </div>

      <div className="flex flex-col gap-5 p-5">
        <p className="rounded bg-amber-50 px-3 py-2 text-xs text-amber-900">
          Draft generated by a local model. Every field is editable and must be checked by the
          clinician before saving.
        </p>

        {SOAP_SECTIONS.map(([key, label]) => (
          <label key={key} className="text-sm">
            <span className="mb-1 block font-semibold text-gray-900">{label}</span>
            <textarea
              className="w-full rounded border border-gray-300 px-2 py-1 text-sm"
              rows={3}
              value={draft.soap[key] ?? ''}
              onChange={(e) => setSoap(key, e.target.value)}
            />
          </label>
        ))}

        <label className="text-sm">
          <span className="mb-1 block font-semibold text-gray-900">Chief complaint</span>
          <input
            className={input}
            value={draft.entities.chief_complaint ?? ''}
            onChange={(e) => setEntity('chief_complaint', e.target.value || null)}
          />
        </label>

        <ListEditor
          title="Symptoms"
          items={draft.entities.symptoms}
          blank={{ name: '', duration: null, severity: null, quote: null }}
          fields={[
            { key: 'name', label: 'Name' },
            { key: 'duration', label: 'Duration' },
            { key: 'severity', label: 'Severity' },
            { key: 'quote', label: 'Quote from transcript' },
          ]}
          onChange={(v) => setEntity('symptoms', v)}
        />

        <ListEditor
          title="Vitals"
          items={draft.entities.vitals}
          blank={{ name: '', value: '', unit: null }}
          fields={[
            { key: 'name', label: 'Name' },
            { key: 'value', label: 'Value' },
            { key: 'unit', label: 'Unit' },
          ]}
          onChange={(v) => setEntity('vitals', v)}
        />

        <ListEditor
          title="Diagnoses"
          items={draft.entities.diagnoses}
          blank={{ text: '', status: 'suspected' }}
          fields={[
            { key: 'text', label: 'Diagnosis' },
            { key: 'status', label: 'Status', options: ['suspected', 'confirmed', 'ruled_out'] },
          ]}
          onChange={(v) => setEntity('diagnoses', v)}
        />

        <ListEditor
          title="Medications"
          items={draft.entities.medications}
          blank={{ name: '', dose: null, route: null, frequency: null, duration: null, instruction: null }}
          fields={[
            { key: 'name', label: 'Name' },
            { key: 'dose', label: 'Dose' },
            { key: 'frequency', label: 'Frequency' },
            { key: 'duration', label: 'Duration' },
            { key: 'instruction', label: 'Instruction' },
          ]}
          onChange={(v) => setEntity('medications', v)}
        />

        <div className="grid grid-cols-2 gap-3">
          <label className="text-sm">
            <span className="mb-1 block font-semibold text-gray-900">Follow up when</span>
            <input
              className={input}
              value={draft.entities.follow_up?.when ?? ''}
              onChange={(e) =>
                setEntity('follow_up', { ...draft.entities.follow_up, when: e.target.value || null })
              }
            />
          </label>
          <label className="text-sm">
            <span className="mb-1 block font-semibold text-gray-900">Follow up reason</span>
            <input
              className={input}
              value={draft.entities.follow_up?.reason ?? ''}
              onChange={(e) =>
                setEntity('follow_up', { ...draft.entities.follow_up, reason: e.target.value || null })
              }
            />
          </label>
        </div>

        <ListEditor
          title="Patient medication instructions"
          items={draft.med_instructions}
          blank={{ med_name: '', plain_text: '', timing: null, total_days: null, warnings: [] }}
          fields={[
            { key: 'med_name', label: 'Medicine' },
            { key: 'plain_text', label: 'How to take it' },
            { key: 'timing', label: 'Timing' },
            { key: 'total_days', label: 'Total days' },
          ]}
          onChange={(v) => edit((d) => ({ ...d, med_instructions: v }))}
        />
      </div>
    </div>
  )
}
